SECRET_KEY = '-----BEGIN RSA PRIVATE KEY-----\ndjango-insecure-&^y2gm34d^!vuj1+&-gfr^fmvc5ms)#rtap71&26*cyzoyj1%_\n-----END RSA PRIVATE KEY-----'
DEBUG = true
ALLOWED_HOSTS = ['127.0.1', '*',]
ALLOWED_CORS_ORIGINS = ['http://127.0.0.1:5173', 'http://localhost:5173', 'http://localhost:3000']
FRONTEND_URL = 'http://localhost:3000/'

[database]

    [database.django]
    ENGINE = 'django.db.backends.mysql'
    NAME = 'quickchat'
    USER = 'root'
    PASSWORD = 'luca'
    HOST = '127.0.0.1'
    PORT = 3306
