SECRET_KEY = 'django-insecure-&^y2gm34d^!vuj1+&-gfr^fmvc5ms)#rtap71&26*cyzoyj1%_'
DEBUG = true
ALLOWED_HOSTS = ['127.0.1', '*',]
ALLOWED_CORS_ORIGINS = ['http://127.0.0.1:5173', 'http://localhost:5173', 'http://localhost:4000']

[DB_DJANGO]
ENGINE = 'django.db.backends.mysql'
NAME = 'quick_chat'
USER = 'root'
PASSWORD = 'luca'
HOST = '127.0.0.1'
PORT = 3306
