# Generated by Django 4.1.1 on 2022-09-18 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('access_code', models.CharField(max_length=8)),
                ('created', models.DateField()),
                ('expiring', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('content', models.CharField(max_length=1024)),
                ('content_type', models.CharField(max_length=40)),
                ('rooms_room', models.ForeignKey(db_column='rooms__room_id', on_delete=django.db.models.deletion.DO_NOTHING, to='chat.rooms')),
                ('users_user', models.ForeignKey(db_column='users__user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinedRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_joined', models.DateField()),
                ('rooms_room', models.ForeignKey(db_column='rooms__room_id', on_delete=django.db.models.deletion.DO_NOTHING, to='chat.rooms')),
                ('users_user', models.ForeignKey(db_column='users__user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_joined_rooms',
            },
        ),
    ]
